config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'
  resources :bees
  root to: redirect('/bees')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bee.rb
class Bee < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bees_controller.rb
class BeesController < ApplicationController
  before_action :set_bee, only: [:show, :edit, :update, :destroy]

  # GET /bees
  # GET /bees.json
  def index
    @bees = Bee.all
  end

  # GET /bees/1
  # GET /bees/1.json
  def show
  end

  # GET /bees/new
  def new
    @bee = Bee.new
  end

  # GET /bees/1/edit
  def edit
  end

  # POST /bees
  # POST /bees.json
  def create
    @bee = Bee.new(bee_params)

    respond_to do |format|
      if @bee.save
        format.html { redirect_to @bee, notice: 'Bee was successfully created.' }
        format.json { render :show, status: :created, location: @bee }
      else
        format.html { render :new }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bees/1
  # PATCH/PUT /bees/1.json
  def update
    respond_to do |format|
      if @bee.update(bee_params)
        format.html { redirect_to @bee, notice: 'Bee was successfully updated.' }
        format.json { render :show, status: :ok, location: @bee }
      else
        format.html { render :edit }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bees/1
  # DELETE /bees/1.json
  def destroy
    @bee.destroy
    respond_to do |format|
      format.html { redirect_to bees_url, notice: 'Bee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bee
      @bee = Bee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bee_params
      params.require(:bee).permit(:descrption, :picture, :adresse)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bees_helper.rb
module BeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bees/_form.html.erb
<%= form_with(model: bee, local: true) do |form| %>
  <% if bee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bee.errors.count, "error") %> prohibited this bee from being saved:</h2>

      <ul>
      <% bee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descrption %>
    <%= form.text_area :descrption %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :bee_picture %>
  </div>

  <div class="field">
    <%= form.label :adresse %>
    <%= form.text_field :adresse %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bees/edit.html.erb
<h1>Editing Bee</h1>

<%= render 'form', bee: @bee %>

<%= link_to 'Show', @bee %> |
<%= link_to 'Back', bees_path %>

app/views/bees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bees</h1>

<table>
  <thead>
    <tr>
      <th>porodica pcelica</th
      <th>Picture</th>
    <strong><th>Adress</th></strong>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bees.each do |bee| %>
      <tr>
        <td><%= bee.descrption %></td>
        <td><%= image_tag bee.picture_url, width: '100%' if bee.picture.present? %></td>
        <td><%= bee.adresse %></td>
        <td><%= link_to 'Show', bee %></td>
        <td><%= link_to 'Edit', edit_bee_path(bee) %></td>
        <td><%= link_to 'Destroy', bee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bee', new_bee_path %>

app/views/bees/new.html.erb
<h1>New Bee</h1>

<%= render 'form', bee: @bee %>

<%= link_to 'Back', bees_path %>

app/views/bees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrption:</strong>
  <%= @bee.descrption %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@bee.picture_url, width: 600) if @bee.picture.present? %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @bee.adresse %>
</p>

<%= link_to 'Edit', edit_bee_path(@bee) %> |
<%= link_to 'Back', bees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('bee.png') %>


    <strong><title>Dragana</title></strong>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <strong><a class="navbar-brand" href="/">bees app</a></strong>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/bees">bees</a></li>
        <li><a href="/pages/info">about</a></li>
      </ul>
    </div>
  </div>
</nav>
    <div class="container">
       <%= yield %>
    </div>
    <footer>
  <div class="container">
    Rails Girls <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<strong><h1>About</h1></strong>
<p>Ja sam jedna fina devojcica, koja voli pcele, i gaji ih, za sve informacije, kontakt:0695894569</p>